#! /usr/bin/env bash

fred_delete -f -k flu-no-behavior
fred_delete -f -k flu-with-behavior

fred_job -k flu-no-behavior -p main-no-behavior.fred -n 4 -m 2
fred_job -k flu-with-behavior -p main.fred -n 4 -m 2

fred_plot -o flatten -k flu-no-behavior,flu-with-behavior \
	  -v INFLUENZA.newExposed,INFLUENZA.newExposed \
	  -t "Flattening the Curve"  \
	  -l NoDistancing,Distancing -d 0 --clean

convert flatten.pdf img/flatten.png
